version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "artlogic"
    open-pull-requests-limit: 100

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "artlogic"
    open-pull-requests-limit: 100

  - package-ecosystem: "docker"
    directory: "/Dockerfile"
    schedule:
      interval: "weekly"
    assignees:
      - "artlogic"
    open-pull-requests-limit: 100
